### PR TITLE
Do not update ExternalIdempotency if it's already set

### LINKED ISSUE #2504: Never Update `PaymentState` `ExternalIdempotency` Data
We need to retry quickly. However, there is a potential race condition for on-chain payments that sign as part of the Authorization step (such as Solana) if we retry too fast:

1. Authorize call 1 (signs)
2. Authorize call 2 starts after 1 begins but before it completes (signs)
3. Authorize call 1 finishes before 2
4. Pay 1 is called after Authorize 1 finishes, but before Authorize 2 finishes
5. Pay 2 is called after Authorize 2 finishes but before Pay 1 finishes
6. Double pay

In the current implementation, this risk is mitigated by proceeding to an `Authorized` state before generating a signed transaction, ensuring that retries go straight to `Pay()`. However, this creates another race condition which, while not a risk, results in undesirable failures:

1. Authorize call
2. Pay call before Authorize persists a signed transaction
3. Pay finds `ExternalIdempotency` data missing and fails immediately

While this doesn't present a double pay risk, it means that we fail unnecessarily when retrying fast. The following changes are needed to both avoid the race condition and the failure.

- Do not proceed to the `Authorized` state until after the signed transaction is persisted to QLDB
- Do not update `ExternalIdempotency` data in QLDB if it is already present

This means that in the case of the first race condition where two Authorize calls are racing, only the first one will have its signed transaction persisted into QLDB. In that case, a race between two Pay calls will be attempting to submit the same signed transaction and there is no risk of double payment.

### PR DESCRIPTION
**Pull request by Sneagan**
### Summary

Closes #2504 

### Type of Change

- [ ] Product feature
- [ ] Bug fix
- [ ] Performance improvement
- [ ] Refactor
- [ ] Other

### Tested Environments

- [ ] Development
- [ ] Staging
- [ ] Production

### Before Requesting Review

- [ ] Does your code build cleanly without any errors or warnings?
- [ ] Have you used auto closing keywords?
- [ ] Have you added tests for new functionality?
- [ ] Have validated query efficiency for new database queries?
- [ ] Have documented new functionality in README or in comments?
- [ ] Have you squashed all intermediate commits?
- [ ] Is there a clear title that explains what the PR does?
- [ ] Have you used intuitive function, variable and other naming?
- [ ] Have you requested security and/or privacy review if needed
- [ ] Have you performed a self review of this PR?

### CODE REVIEW

File: services/payments/statemachine.go [hunk 1]
```diff
@@ -213,6 +214,28 @@ func (s *Service) DriveTransaction(
...
+			return fmt.Errorf("failed to validate payment state history", err)
+		}
+		// If there is idempotency data in qldb and it is different from the idempotency data in the
+		// current state it means that there was a race between two calls to Authenticate and we are
+		// operating on the loser. There is no risk to proceeding as long as we retain the winner
+		// idempotency.
+		if !bytes.Equal(state.ExternalIdempotency, persistedState.ExternalIdempotency) &&
+			persistedState != nil {
+			state.ExternalIdempotency = persistedState.ExternalIdempotency
+		}
```
Comment (pavelbrm) [inline services/payments/statemachine.go:237]: Seems like it's safer to check `persistedState` to not be `nil`, and then access the `ExternalIdempotency` field. 😉 

```suggestion
		if persistedState != nil && !bytes.Equal(state.ExternalIdempotency, persistedState.ExternalIdempotency) {
			state.ExternalIdempotency = persistedState.ExternalIdempotency
		}
```

**Review by pavelbrm — APPROVED** [review]
