### PR TITLE
fix vault signing in create-tokens

### LINKED ISSUE #35: implement vault for create-tokens

### PR DESCRIPTION
**Pull request by maikelmclauflin**
fixes #35

### CODE REVIEW

File: utils/vaultsigner/vaultsigner.go [hunk 1]
```diff
@@ -70,9 +71,14 @@ func (vs *VaultSigner) String() string {
 	return hex.EncodeToString(publicKey)
 }
 
+// Algs returns the algs for signing key to check
```
Comment (evq) [inline utils/vaultsigner/vaultsigner.go]: I think we can remove this
